env:
- TEST_SUITE=test
- TEST_SUITE=travis-dist-test
- TEST_SUITE=dialyzer-travis

script: make all && make $TEST_SUITE

language: erlang
otp_release:
    - R16B02
services:
    - cassandra

cache:
  apt: true
  directories:
    - deps

after_failure:
- find _build/devrels/dev*/log -name '*.log' | while read filename; do echo "$filename"; cat "$filename"; done
